# Builds using pip and tests using pytest

name: Linux 3.6 | 3.7 | 3.8

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        py: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.py}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy scipy pandas matplotlib shapely meshio pytest
    - name: Build and Install
      run: pip install .
    - name: Test
      run: pytest